version: "1.0"
info:
  model: int-scaffold
packages:
- name: SerengetiGithub1806Project
  gitServerName: srcGithubCtrl_Arti
  gitUrl: https://github.com/ArtiKhareIBM
  gitUsername: ArtiKhareIBM
  gitBranch: main
- name: LowerFSPackage
  version: "1.0"
  gitServerName: RAHS_GH_IBMAccount_SD
  gitUrl: https://github.com/ArtiKhareIBM
  gitUsername: rahul-singh-IBM-68
  gitBranch: main
services:
- serviceName: project.serengetigithub1806.integrations:lowerfs_account_changed
  packages:
  - name: SerengetiGithub1806Project
    version: "1.0"
  - name: LowerFSPackage
    version: "1.0"
- serviceName: LowerFSPackage:lowerFS
  packages:
  - name: LowerFSPackage
    version: "1.0"
- serviceName: pub.string:toLower
  packages:
  - name: WmPublic
    version: 11.1.0.0.2068
